import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export type Intent = "POSITIVE" | "NEGATIVE" | "NEUTRAL";

export async function classifyIntent(replyText: string): Promise<Intent> {
  const message = await client.messages.create({
    model: "claude-opus-4-5",
    max_tokens: 10,
    messages: [
      {
        role: "user",
        content:
          `Classify the following SMS reply from a business owner as POSITIVE, NEGATIVE, or NEUTRAL. ` +
          `POSITIVE means they are interested in getting a website built. ` +
          `NEGATIVE means they are not interested or want to opt out. ` +
          `NEUTRAL means ambiguous or unclear intent. ` +
          `Reply with ONLY one word: POSITIVE, NEGATIVE, or NEUTRAL.\n\nReply: "${replyText}"`,
      },
    ],
  });

  const text = message.content
    .filter((b) => b.type === "text")
    .map((b) => (b as { type: "text"; text: string }).text)
    .join("")
    .trim()
    .toUpperCase();

  if (text.includes("POSITIVE")) return "POSITIVE";
  if (text.includes("NEGATIVE")) return "NEGATIVE";
  return "NEUTRAL";
}

export interface GeneratedSite {
  files: Array<{ path: string; content: string }>;
  slug: string;
  envVars: Record<string, string>;
}

interface LeadData {
  business_name: string;
  phone: string;
  address?: string | null;
  category?: string | null;
  rating?: number | null;
  review_count?: number | null;
  maps_url?: string | null;
  hours?: string | null;
}

export async function generateWebsite(lead: LeadData): Promise<GeneratedSite> {
  const leadJson = JSON.stringify(
    {
      business_name: lead.business_name,
      phone: lead.phone,
      address: lead.address,
      category: lead.category,
      rating: lead.rating,
      review_count: lead.review_count,
      maps_url: lead.maps_url,
      hours: lead.hours,
    },
    null,
    2
  );

  const prompt = `Build a complete FastAPI + React 19 website for this business.
Business data: ${leadJson}

Determine industry and colour scheme. Generate 10-20 services in 3-5 categories.
Write 6 SEO articles (750-1200 words, Unsplash image URLs).
FastAPI: MongoDB, Motor, JWT, OpenAI chatbot via emergentintegrations.
React 19: Tailwind, shadcn/ui.
Pages: Home, Services, Articles, Contact, Booking (3-step wizard with HourlyCalendar: day/week views, colour-coded slots, double-booking prevention).
Admin: stats cards, calendar, customer manager, chat history.
Train chatbot on business data.
Return files as <files><file><path/><content/></file></files> plus <slug> and <env_vars>.
No placeholders.`;

  const message = await client.messages.create({
    model: "claude-opus-4-5",
    max_tokens: 32000,
    messages: [{ role: "user", content: prompt }],
  });

  const responseText = message.content
    .filter((b) => b.type === "text")
    .map((b) => (b as { type: "text"; text: string }).text)
    .join("");

  return parseGeneratedSite(responseText, lead.business_name);
}

function parseGeneratedSite(response: string, businessName: string): GeneratedSite {
  const files: Array<{ path: string; content: string }> = [];

  // Parse <files><file><path>...</path><content>...</content></file></files>
  const filesBlockMatch = response.match(/<files>([\s\S]*?)<\/files>/);
  if (filesBlockMatch) {
    const filesBlock = filesBlockMatch[1];
    const fileRegex = /<file>\s*<path>([\s\S]*?)<\/path>\s*<content>([\s\S]*?)<\/content>\s*<\/file>/g;
    let match: RegExpExecArray | null;
    while ((match = fileRegex.exec(filesBlock)) !== null) {
      files.push({
        path: match[1].trim(),
        content: match[2].trim(),
      });
    }
  }

  // Parse <slug>...</slug>
  const slugMatch = response.match(/<slug>([\s\S]*?)<\/slug>/);
  const slug = slugMatch
    ? slugMatch[1].trim()
    : slugify(businessName);

  // Parse <env_vars>...</env_vars>
  const envVars: Record<string, string> = {};
  const envBlockMatch = response.match(/<env_vars>([\s\S]*?)<\/env_vars>/);
  if (envBlockMatch) {
    const lines = envBlockMatch[1].trim().split("\n");
    for (const line of lines) {
      const eqIdx = line.indexOf("=");
      if (eqIdx > 0) {
        const key = line.slice(0, eqIdx).trim();
        const value = line.slice(eqIdx + 1).trim();
        if (key) envVars[key] = value;
      }
    }
  }

  // If no files were parsed, create a minimal placeholder so the build doesn't fail silently
  if (files.length === 0) {
    console.warn("[Claude] No files parsed from response – creating minimal README");
    files.push({
      path: "README.md",
      content: `# ${businessName} Website\n\nGenerated by LeadForge AI\n`,
    });
  }

  return { files, slug, envVars };
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}
